import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbars"; // ✅ Fixed import
import Footer from "./component/Footer";
// import { useRouter } from 'next/router'; // Import useRouter

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const router = useRouter();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Conditionally render the Navbar based on the route */}
        {/* {router.pathname !== '/dashboard' && } */}
      <Navbar/>
        {children}
        <Footer/>
     
      </body>
    </html>
  );
}
